version: 0.0
os: linux

files:
  - source: /
    destination: /home/damien/server

permissions:
  - object: /
    pattern: "**"
    owner: damien
    group: damien

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 300
      runas: damien
  AfterInstall:
    - location: fix_privileges.sh
      timeout: 300
      runas: damien
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: damien
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: damien
