spring:
  main:
    banner-mode: off
  data:
    mongodb:
      host: 172.17.0.1
      port: 27017
      database: mrp
      username: mrp-user
      password: mrppass*J
      authentication-database: admin

logging.level.org.springframework.data.mongodb:
  repository.Query: DEBUG
  core.MongoTemplate: DEBUG

